# Day 4 – Pandas Basics

## Objective

Learn the fundamentals of Pandas by loading a CSV dataset and exploring its structure.

## Topics Covered

- Importing Pandas
- Loading CSV Files
- Viewing Dataset
- First & Last Rows
- Dataset Information
- Shape
- Columns
- Data Types
- Summary Statistics
- Missing Values
- Filtering Data
- Sorting Data
- Value Counts

## Technologies

- Python
- Pandas
- Google Colab

## Dataset

student_data.csv

## Run

1. Open Google Colab
2. Upload `student_data.csv`
3. Run all notebook cells

## Learning Outcome

- Successfully loaded a CSV dataset
- Explored rows and columns
- Retrieved dataset information
- Performed basic data analysis using Pandas

## Author

**Shwetaparna dash**  
Data Science Intern  
Codomax Digital Solutions

TASK-4

Import Pandas

In [ ]:
import pandas as pd

print("Pandas Version:", pd.__version__)

Pandas Version: 2.2.2

Upload CSV File

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving student_data.csv to student_data.csv

Load Dataset

In [ ]:
df = pd.read_csv("student_data.csv")

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

Display Dataset

In [ ]:
df

,Student_ID,Name,Age,Gender,Course,Marks,City
0,101,Gopal,21,Male,Data Science,96,Bhubaneswar
1,102,Shweta,21,Female,Machine Learning,94,Cuttack
2,103,Anu,20,Female,Data Science,88,New York
3,104,Hari,21,Male,Machine Learning,92,Chicago
4,105,Kiran,19,Male,Python,79,Houston
5,106,Diana,22,Female,Artificial Intelligence,95,Boston
6,107,Ethan,20,Male,Data Science,84,Seattle
7,108,Fiona,21,Female,Python,90,San Francisco
8,109,George,23,Male,Machine Learning,87,Miami
9,110,Hannah,20,Female,Data Analytics,91,Dallas
10,111,Ian,22,Male,Artificial Intelligence,85,Denver
11,112,Julia,21,Female,Data Science,93,Los Angeles
12,113,Kevin,20,Male,Python,81,Phoenix
13,114,Laura,22,Female,Machine Learning,89,Atlanta
14,115,Michael,21,Male,Data Science,86,Las Vegas
15,116,Nancy,20,Female,Data Analytics,90,San Diego
16,117,Oliver,23,Male,Artificial Intelligence,94,Austin
17,118,Patricia,21,Female,Python,88,Portland
18,119,Quentin,22,Male,Machine Learning,83,Nashville
19,120,Rachel,20,Female,Data Science,91,Orlando
20,121,Samuel,21,Male,Artificial Intelligence,87,Columbus
21,122,Tina,22,Female,Python,92,Charlotte
22,123,Umar,20,Male,Data Analytics,80,Detroit
23,124,Victoria,21,Female,Machine Learning,95,Indianapolis
24,125,William,22,Male,Data Science,89,San Jose
25,126,Xenia,20,Female,Python,86,Jacksonville
26,127,Yash,21,Male,Artificial Intelligence,93,Pune
27,128,Zara,22,Female,Data Analytics,90,Mumbai
28,129,Aarav,20,Male,Machine Learning,84,Delhi
29,130,Ananya,21,Female,Data Science,91,Bengaluru
30,131,Rohan,22,Male,Python,82,Hyderabad
31,132,Priya,20,Female,Artificial Intelligence,94,Chennai
32,133,Aditya,21,Male,Machine Learning,88,Kolkata
33,134,Neha,22,Female,Data Analytics,89,Jaipur
34,135,Karan,20,Male,Data Science,85,Lucknow
35,136,Pooja,21,Female,Python,90,Surat
36,137,Rahul,22,Male,Artificial Intelligence,92,Nagpur
37,138,Sneha,20,Female,Machine Learning,87,Visakhapatnam
38,139,Arjun,21,Male,Data Analytics,83,Bhopal
39,140,Kavya,22,Female,Data Science,95,Coimbatore
40,141,Vikram,20,Male,Python,81,Patna
41,142,Ishita,21,Female,Artificial Intelligence,93,Raipur
42,143,Manish,22,Male,Machine Learning,86,Noida
43,144,Meera,20,Female,Data Science,90,Gurugram
44,145,Ritesh,21,Male,Python,84,Amritsar
45,146,Simran,22,Female,Data Analytics,91,Chandigarh
46,147,Harsh,20,Male,Artificial Intelligence,88,Ranchi
47,148,Aisha,21,Female,Machine Learning,94,Thiruvananthapuram
48,149,Nikhil,22,Male,Data Science,87,Mysuru
49,150,Diya,20,Female,Python,92,Vadodara

First Five Rows

In [ ]:
df.head()

   Student_ID    Name  Age  Gender            Course  Marks         City
0         101  Gopal    21    Male      Data Science     96  Bhubaneswar
1         102  Shweta   21  Female  Machine Learning     94      Cuttack
2         103     Anu   20  Female      Data Science     88     New York
3         104    Hari   21    Male  Machine Learning     92      Chicago
4         105   Kiran   19    Male            Python     79      Houston

Last Five Rows

In [ ]:
df.tail()

,Student_ID,Name,Age,Gender,Course,Marks,City
45,146,Simran,22,Female,Data Analytics,91,Chandigarh
46,147,Harsh,20,Male,Artificial Intelligence,88,Ranchi
47,148,Aisha,21,Female,Machine Learning,94,Thiruvananthapuram
48,149,Nikhil,22,Male,Data Science,87,Mysuru
49,150,Diya,20,Female,Python,92,Vadodara

Dataset Information

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  50 non-null     int64
 1   Name        50 non-null     object
 2   Age         50 non-null     int64
 3   Gender      50 non-null     object
 4   Course      50 non-null     object
 5   Marks       50 non-null     int64
 6   City        50 non-null     object
dtypes: int64(3), object(4)
memory usage: 2.9+ KB

Dataset Shape

In [ ]:
print("Rows and Columns:", df.shape)

Rows and Columns: (50, 7)

Column Names

In [ ]:
print(df.columns)

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Course', 'Marks', 'City'], dtype='object')

Data Types

In [ ]:
print(df.dtypes)

Student_ID     int64
Name          object
Age            int64
Gender        object
Course        object
Marks          int64
City          object
dtype: object

Statistical Summary

In [ ]:
df.describe()

       Student_ID       Age      Marks
count    50.00000  50.00000  50.000000
mean    125.50000  21.00000  88.680000
std      14.57738   0.92582   4.381967
min     101.00000  19.00000  79.000000
25%     113.25000  20.00000  86.000000
50%     125.50000  21.00000  89.000000
75%     137.75000  22.00000  92.000000
max     150.00000  23.00000  96.000000

Check Missing Values

In [ ]:
df.isnull().sum()

Student_ID    0
Name          0
Age           0
Gender        0
Course        0
Marks         0
City          0
dtype: int64

Display Specific Columns

In [ ]:
df[["Name","Course","Marks"]]

        Name                   Course  Marks
0     Gopal              Data Science     96
1     Shweta         Machine Learning     94
2        Anu             Data Science     88
3       Hari         Machine Learning     92
4      Kiran                   Python     79
5      Diana  Artificial Intelligence     95
6      Ethan             Data Science     84
7      Fiona                   Python     90
8     George         Machine Learning     87
9     Hannah           Data Analytics     91
10       Ian  Artificial Intelligence     85
11     Julia             Data Science     93
12     Kevin                   Python     81
13     Laura         Machine Learning     89
14   Michael             Data Science     86
15     Nancy           Data Analytics     90
16    Oliver  Artificial Intelligence     94
17  Patricia                   Python     88
18   Quentin         Machine Learning     83
19    Rachel             Data Science     91
20    Samuel  Artificial Intelligence     87
21      Tina                   Python     92
22      Umar           Data Analytics     80
23  Victoria         Machine Learning     95
24   William             Data Science     89
25     Xenia                   Python     86
26      Yash  Artificial Intelligence     93
27      Zara           Data Analytics     90
28     Aarav         Machine Learning     84
29    Ananya             Data Science     91
30     Rohan                   Python     82
31     Priya  Artificial Intelligence     94
32    Aditya         Machine Learning     88
33      Neha           Data Analytics     89
34     Karan             Data Science     85
35     Pooja                   Python     90
36     Rahul  Artificial Intelligence     92
37     Sneha         Machine Learning     87
38     Arjun           Data Analytics     83
39     Kavya             Data Science     95
40    Vikram                   Python     81
41    Ishita  Artificial Intelligence     93
42    Manish         Machine Learning     86
43     Meera             Data Science     90
44    Ritesh                   Python     84
45    Simran           Data Analytics     91
46     Harsh  Artificial Intelligence     88
47     Aisha         Machine Learning     94
48    Nikhil             Data Science     87
49      Diya                   Python     92

Students with Marks Above 90

In [ ]:
high_marks = df[df["Marks"] > 90]

high_marks

,Student_ID,Name,Age,Gender,Course,Marks,City
0,101,Gopal,21,Male,Data Science,96,Bhubaneswar
1,102,Shweta,21,Female,Machine Learning,94,Cuttack
3,104,Hari,21,Male,Machine Learning,92,Chicago
5,106,Diana,22,Female,Artificial Intelligence,95,Boston
9,110,Hannah,20,Female,Data Analytics,91,Dallas
11,112,Julia,21,Female,Data Science,93,Los Angeles
16,117,Oliver,23,Male,Artificial Intelligence,94,Austin
19,120,Rachel,20,Female,Data Science,91,Orlando
21,122,Tina,22,Female,Python,92,Charlotte
23,124,Victoria,21,Female,Machine Learning,95,Indianapolis
26,127,Yash,21,Male,Artificial Intelligence,93,Pune
29,130,Ananya,21,Female,Data Science,91,Bengaluru
31,132,Priya,20,Female,Artificial Intelligence,94,Chennai
36,137,Rahul,22,Male,Artificial Intelligence,92,Nagpur
39,140,Kavya,22,Female,Data Science,95,Coimbatore
41,142,Ishita,21,Female,Artificial Intelligence,93,Raipur
45,146,Simran,22,Female,Data Analytics,91,Chandigarh
47,148,Aisha,21,Female,Machine Learning,94,Thiruvananthapuram
49,150,Diya,20,Female,Python,92,Vadodara

Average Marks

In [ ]:
print("Average Marks:", df["Marks"].mean())

Average Marks: 88.68

Maximum & Minimum Marks

In [ ]:
print("Highest Marks:", df["Marks"].max())
print("Lowest Marks:", df["Marks"].min())

Highest Marks: 96
Lowest Marks: 79

Sort by Marks

In [ ]:
df.sort_values(by="Marks", ascending=False)

,Student_ID,Name,Age,Gender,Course,Marks,City
0,101,Gopal,21,Male,Data Science,96,Bhubaneswar
5,106,Diana,22,Female,Artificial Intelligence,95,Boston
39,140,Kavya,22,Female,Data Science,95,Coimbatore
23,124,Victoria,21,Female,Machine Learning,95,Indianapolis
1,102,Shweta,21,Female,Machine Learning,94,Cuttack
16,117,Oliver,23,Male,Artificial Intelligence,94,Austin
31,132,Priya,20,Female,Artificial Intelligence,94,Chennai
47,148,Aisha,21,Female,Machine Learning,94,Thiruvananthapuram
11,112,Julia,21,Female,Data Science,93,Los Angeles
26,127,Yash,21,Male,Artificial Intelligence,93,Pune
41,142,Ishita,21,Female,Artificial Intelligence,93,Raipur
36,137,Rahul,22,Male,Artificial Intelligence,92,Nagpur
21,122,Tina,22,Female,Python,92,Charlotte
3,104,Hari,21,Male,Machine Learning,92,Chicago
49,150,Diya,20,Female,Python,92,Vadodara
9,110,Hannah,20,Female,Data Analytics,91,Dallas
19,120,Rachel,20,Female,Data Science,91,Orlando
45,146,Simran,22,Female,Data Analytics,91,Chandigarh
29,130,Ananya,21,Female,Data Science,91,Bengaluru
35,136,Pooja,21,Female,Python,90,Surat
15,116,Nancy,20,Female,Data Analytics,90,San Diego
7,108,Fiona,21,Female,Python,90,San Francisco
27,128,Zara,22,Female,Data Analytics,90,Mumbai
43,144,Meera,20,Female,Data Science,90,Gurugram
33,134,Neha,22,Female,Data Analytics,89,Jaipur
24,125,William,22,Male,Data Science,89,San Jose
13,114,Laura,22,Female,Machine Learning,89,Atlanta
46,147,Harsh,20,Male,Artificial Intelligence,88,Ranchi
32,133,Aditya,21,Male,Machine Learning,88,Kolkata
17,118,Patricia,21,Female,Python,88,Portland
2,103,Anu,20,Female,Data Science,88,New York
8,109,George,23,Male,Machine Learning,87,Miami
37,138,Sneha,20,Female,Machine Learning,87,Visakhapatnam
48,149,Nikhil,22,Male,Data Science,87,Mysuru
20,121,Samuel,21,Male,Artificial Intelligence,87,Columbus
14,115,Michael,21,Male,Data Science,86,Las Vegas
25,126,Xenia,20,Female,Python,86,Jacksonville
42,143,Manish,22,Male,Machine Learning,86,Noida
34,135,Karan,20,Male,Data Science,85,Lucknow
10,111,Ian,22,Male,Artificial Intelligence,85,Denver
6,107,Ethan,20,Male,Data Science,84,Seattle
44,145,Ritesh,21,Male,Python,84,Amritsar
28,129,Aarav,20,Male,Machine Learning,84,Delhi
18,119,Quentin,22,Male,Machine Learning,83,Nashville
38,139,Arjun,21,Male,Data Analytics,83,Bhopal
30,131,Rohan,22,Male,Python,82,Hyderabad
40,141,Vikram,20,Male,Python,81,Patna
12,113,Kevin,20,Male,Python,81,Phoenix
22,123,Umar,20,Male,Data Analytics,80,Detroit
4,105,Kiran,19,Male,Python,79,Houston

Course-wise Student Count

In [ ]:
df["Course"].value_counts()

Course
Data Science               12
Machine Learning           11
Python                     11
Artificial Intelligence     9
Data Analytics              7
Name: count, dtype: int64

Final Output

In [ ]:
print("="*60)
print("Day 4 Task Completed Successfully")
print("Pandas Basics")
print("Dataset Loaded and Analyzed Successfully")
print("Organization : Codomax Digital Solutions")
print("="*60)

============================================================
Day 4 Task Completed Successfully
Pandas Basics
Dataset Loaded and Analyzed Successfully
Organization : Codomax Digital Solutions
============================================================